/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.21
 * Generated at: 2022-06-28 05:56:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import dao.CRUD;
import java.util.Date;
import java.text.SimpleDateFormat;
import dao.Livro;

public final class editar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("dao.CRUD");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("dao.Livro");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Web Livros-editar</title>\r\n");
      out.write("	<!-- css -->\r\n");
      out.write("	<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("	<!-- js -->\r\n");
      out.write("	<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<form id=\"editar\" method=\"post\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<!-- Nome do Livro -->\r\n");
      out.write("			<div class=\"row \">\r\n");
      out.write("				<div class=\"col-8 \" style=\"margin-top: 20px;\">\r\n");
      out.write("					<label class=\"form-label\">Nome do Livro:</label> <input type=\"text\"\r\n");
      out.write("						name=\"nomelivro\" id=\"nomelivro\" class=\"form-control\"\r\n");
      out.write("						aria-describedby=\"passwordHelpBlock\"\r\n");
      out.write("						value=\"");
      out.print(request.getParameter("nome"));
      out.write("\" required>\r\n");
      out.write("				</div>				\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Nome do Autor(a) -->\r\n");
      out.write("			<div class=\"row \">\r\n");
      out.write("				<div class=\"col-8 \" style=\"margin-top: 20px;\">\r\n");
      out.write("					<label class=\"form-label\">Nome do Autor:</label> <input type=\"text\"\r\n");
      out.write("						name=\"autorlivro\" id=\"autorlivro\" class=\"form-control\"\r\n");
      out.write("						aria-describedby=\"passwordHelpBlock\"\r\n");
      out.write("						value=\"");
      out.print(request.getParameter("autor"));
      out.write("\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Editora -->\r\n");
      out.write("			<div class=\"row \">\r\n");
      out.write("				<div class=\"col-8 \" style=\"margin-top: 20px;\">\r\n");
      out.write("					<label class=\"form-label\">Editora:</label> <input type=\"text\"\r\n");
      out.write("						name=\"editoralivro\" id=\"editoralivro\" class=\"form-control\"\r\n");
      out.write("						aria-describedby=\"passwordHelpBlock\"\r\n");
      out.write("						value=\"");
      out.print(request.getParameter("editor"));
      out.write("\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Data de Lançamento-->\r\n");
      out.write("			<div class=\"row \">\r\n");
      out.write("				<div class=\"col-4 \" style=\"margin-top: 20px;\">\r\n");
      out.write("					<label class=\"form-label\">Data de lançamento:</label> <input\r\n");
      out.write("						type=\"Date\" name=\"datalivro\" id=\"datalivro\" class=\"form-control\"\r\n");
      out.write("						aria-describedby=\"passwordHelpBlock\"\r\n");
      out.write("						value=\"");
      out.print(request.getParameter("data"));
      out.write("\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>			\r\n");
      out.write("			<br>\r\n");
      out.write("			<!-- Botão Atualizar-->\r\n");
      out.write("			<button type=\"submit\" name=\"botaoAtualizar\" class=\"btn btn-success\">Atualizar</button>\r\n");
      out.write("			<!-- Botão Voltar-->\r\n");
      out.write("			<a href=\"index.jsp\"><button name=\"voltar\" type=\"button\" class=\"btn btn-primary\">Voltar</button></a>		\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>		\r\n");
      out.write("	");

	if (request.getParameter("botaoAtualizar")!= null) {

		CRUD crud = new CRUD();
		crud.conectar();
		String nome = request.getParameter("nomelivro");
		String autor = request.getParameter("autorlivro");
		String editora = request.getParameter("editoralivro");
		String data = request.getParameter("datalivro");
		String idLivro = request.getParameter("id");

		SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
		formater.parse(data);
		
		Livro l = new Livro(idLivro, nome, autor, editora, formater.parse(data));
		
		crud.editarLivro(l);			
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
